updage

diff --git a/.github/workflows/IMwrt-24.10-6.6.yml b/.github/workflows/IMwrt-24.10-6.6.yml
--- a/.github/workflows/IMwrt-24.10-6.6.yml
+++ b/.github/workflows/IMwrt-24.10-6.6.yml
@@ -415,7 +415,18 @@ jobs:
         working-directory: ./openwrt
         run: |
           # 获取固件版本
-          FW_VERSION=$(grep 'REVISION:=' include/version.mk | cut -d'=' -f2 | xargs)
+          # FW_VERSION=$(grep 'REVISION:=' include/version.mk | cut -d'=' -f2 | xargs)
+          # echo "FW_VERSION=${FW_VERSION}" >> $GITHUB_OUTPUT
+
+          if [ ! -f include/version.mk ]; then
+            echo "Error: include/version.mk not found"
+            exit 1
+          fi
+          FW_VERSION=$(awk -F ':=' '/VERSION_NUMBER:=/ {print $2}' include/version.mk | xargs)
+          if [ -z "$FW_VERSION" ]; then
+            echo "Error: Failed to extract VERSION_NUMBER"
+            exit 1
+          fi
           echo "FW_VERSION=${FW_VERSION}" >> $GITHUB_OUTPUT
 
           # 获取内核版本 (从 .config 文件)
@@ -432,7 +443,10 @@ jobs:
         run: |
           set -e
           cd openwrt
-          make -j$(nproc) || make -j4 || make -j1 V=s
+          echo -e "$(( $(nproc) * 3 / 2 )) 线程编译，启用 ccache"
+          make -j$(( $(nproc) * 3 / 2 )) CCACHE=1 || make -j1 CCACHE=1 V=s
+
+          # make -j$(nproc) || make -j4 || make -j1 V=s
           echo "status=success" >> $GITHUB_OUTPUT
           echo "DEVICE_NAME=_${{ matrix.device_model }}" >> $GITHUB_ENV
           echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
